import {db} from "./db";

const catorgies = [
  {name: "Technology"},
  {name: "Fashion"},
  {name: "Food & Drink"},
  {name: "Health & Wellness"},
  {name: "Travel"},
  {name: "Home & Garden"},
  {name: "Finance"},
  {name: "Sports & Fitness"},
  {name: "Arts & Crafts"},
  {name: "Automotive"},
  {name: "Education"},
  {name: "Entertainment"},
  {name: "Beauty"},
  {name: "Pets"},
  {name: "Parenting"},
  {name: "Books & Literature"},
  {name: "Science"},
  {name: "Business"},
  {name: "DIY & Home Improvement"},
  {name: "Music"},
  {name: "Photography"},
  {name: "Gaming"},
  {name: "Cooking & Recipes"},
  {name: "Shopping"},
  {name: "Environment & Sustainability"},
  {name: "Self-Improvement"},
  {name: "Relationships"},
  {name: "History"},
  {name: "Spirituality"},
  {name: "Technology Gadgets"},
  {name: "Fashion Accessories"},
  {name: "Cuisine"},
  {name: "Fitness"},
  {name: "Adventure Travel"},
  {name: "Interior Design"},
  {name: "Investing"},
  {name: "Outdoor Recreation"},
  {name: "Visual Arts"},
  {name: "Nutrition"},
  {name: "Hobbies"},
  {name: "Luxury Lifestyle"},
  {name: "Medical Science"},
  {name: "Marketing"},
  {name: "Crafts"},
  {name: "Vehicles"},
  {name: "Online Learning"},
  {name: "Movies & Film"},
  {name: "Hair & Makeup"},
  {name: "Animal Care"},
  {name: "Child Development"},
  {name: "Literary Fiction"},
  {name: "Space Exploration"},
  {name: "Entrepreneurship"},
  {name: "DIY Projects"},
  {name: "Music Production"},
  {name: "Digital Photography"},
  {name: "Console Gaming"},
  {name: "Baking & Desserts"},
  {name: "E-commerce"},
  {name: "Climate Change"},
  {name: "Personal Finance"},
  {name: "Yoga & Meditation"},
  {name: "Weddings"},
  {name: "Travel Tips & Guides"},
  {name: "Home Decor"},
  {name: "Cryptocurrency"},
  {name: "Psychology"},
  {name: "Parenting Advice"},
  {name: "Short Stories"},
  {name: "Astronomy"},
  {name: "Small Business Management"},
  {name: "Woodworking"},
  {name: "Fashion Trends"},
  {name: "Regional Cuisine"},
  {name: "Strength Training"},
  {name: "Backpacking"},
  {name: "Graphic Design"},
  {name: "Stock Market Investing"},
  {name: "Adventure Sports"},
  {name: "Sculpture"},
  {name: "Diet & Weight Loss"},
  {name: "Collecting"},
  {name: "Luxury Travel"},
  {name: "Sustainable Living"},
  {name: "Motivational"},
  {name: "Marriage Advice"},
  {name: "Fantasy Fiction"},
  {name: "Astrophysics"},
  {name: "Startups"},
  {name: "Craftsmanship"},
  {name: "Street Fashion"},
  {name: "Seafood"},
  {name: "Cardiovascular Health"},
  {name: "Gardening"},
  {name: "Futurism"},
  {name: "Time Management"},
  {name: "Single Parenting"},
  {name: "Poetry"},
  {name: "Geology"},
  {name: "Customer Service"},
];
export const createCategory = async () => {
  try {
    // Use Prisma Client to insert categories into the database
    await db.category.createMany({
      data: catorgies,
    });

    console.log("Categories have been added to the database.");
  } catch (error) {
    console.error("Error adding categories:", error);
  }
};
