import {db} from "./db";

const catorgies = [
  {name: "Electronic"},
  {name: "Metal"},
  {name: "Blues"},
  {name: "Stage And Screen"},
  {name: "Metal"},
  {name: "Electronic"},
  {name: "Rap"},
  {name: "Pop"},
  {name: "Electronic"},
  {name: "Reggae"},
  {name: "Classical"},
  {name: "Blues"},
  {name: "Folk"},
  {name: "World"},
  {name: "Rock"},
  {name: "Reggae"},
  {name: "Non Music"},
  {name: "Latin"},
  {name: "Stage And Screen"},
  {name: "Soul"},
  {name: "Jazz"},
  {name: "Pop"},
  {name: "Non Music"},
  {name: "Classical"},
  {name: "Pop"},
  {name: "Folk"},
  {name: "Latin"},
  {name: "Blues"},
  {name: "Pop"},
  {name: "Non Music"},
  {name: "Metal"},
  {name: "Country"},
  {name: "Hip Hop"},
  {name: "World"},
  {name: "Pop"},
  {name: "Hip Hop"},
  {name: "Blues"},
  {name: "Electronic"},
  {name: "Electronic"},
  {name: "Latin"},
  {name: "Soul"},
  {name: "Non Music"},
  {name: "Folk"},
  {name: "Funk"},
  {name: "Electronic"},
  {name: "Folk"},
  {name: "Folk"},
  {name: "Blues"},
  {name: "Metal"},
  {name: "Hip Hop"},
  {name: "Latin"},
  {name: "World"},
  {name: "Stage And Screen"},
  {name: "Blues"},
  {name: "Folk"},
  {name: "Funk"},
  {name: "Country"},
  {name: "Funk"},
  {name: "Reggae"},
  {name: "Country"},
  {name: "Soul"},
  {name: "World"},
  {name: "World"},
  {name: "Rap"},
  {name: "Hip Hop"},
  {name: "Pop"},
  {name: "Classical"},
  {name: "Country"},
  {name: "Hip Hop"},
  {name: "Hip Hop"},
  {name: "Electronic"},
  {name: "Blues"},
  {name: "Latin"},
  {name: "World"},
  {name: "Folk"},
  {name: "Folk"},
  {name: "Funk"},
  {name: "Blues"},
  {name: "Folk"},
  {name: "Reggae"},
  {name: "Stage And Screen"},
  {name: "Non Music"},
  {name: "Rap"},
  {name: "Hip Hop"},
  {name: "Soul"},
  {name: "Pop"},
  {name: "Rock"},
  {name: "Metal"},
  {name: "Country"},
  {name: "Hip Hop"},
  {name: "Latin"},
  {name: "Latin"},
  {name: "Hip Hop"},
  {name: "Classical"},
  {name: "Metal"},
  {name: "Soul"},
  {name: "Metal"},
  {name: "Country"},
  {name: "Hip Hop"},
  {name: "Jazz"},
];

export const createCategory = async () => {
  try {
    // Use Prisma Client to insert categories into the database
    await db.category.createMany({
      data: catorgies,
    });

    console.log("Categories have been added to the database.");
  } catch (error) {
    console.error("Error adding categories:", error);
  }
};
